FROM microsoft/windowsservercore:10.0.14300.1030

# Create directory
RUN mkdir NDP
WORKDIR NDP

# This file should have previously been downloaded
COPY NDP462-KB3151800-x86-x64-AllOS-ENU.exe .

# Because the image doesn't support UI, use /q
RUN NDP462-KB3151800-x86-x64-AllOS-ENU.exe /q

CMD [ "cmd" ]
